# Generated by Django 4.1.7 on 2023-04-22 03:25

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_room_name', models.CharField(blank=True, max_length=30)),
                ('meeting_room_number', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=30)),
                ('sponsor_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='./images')),
                ('recurrences', recurrence.fields.RecurrenceField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.categories')),
                ('meeting_room', models.ManyToManyField(to='list.meetingrooms')),
                ('sponsor', models.ManyToManyField(to='list.sponsorname')),
            ],
        ),
    ]
