# Generated by Django 4.1.7 on 2023-04-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='')),
                ('sponsor', models.CharField(max_length=30)),
                ('sponsor_email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('STEM', 'STEM'), ('READWRITE', 'Reading/Writing'), ('FUN', 'Fun'), ('FINEART', 'Fine Arts'), ('POLITICS', 'Politics'), ('LANGUAGE', 'Language'), ('SPORTS', 'Sports'), ('ACTIVISMVOLUNTEER', 'Activism/Volunteering'), ('STUDUNION', 'Student Unions'), ('COMP', 'Competition'), ('BUSI', 'Business'), ('LEAD', 'Leadership')], max_length=17)),
            ],
        ),
    ]
