# Generated by Django 4.1.7 on 2023-04-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
