# Generated by Django 4.1.7 on 2023-04-22 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='google_classroom_code',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.MinLengthValidator(limit_value=6)]),
        ),
    ]
