# Generated by Django 4.1.7 on 2023-04-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='picture',
            field=models.ImageField(upload_to='./images'),
        ),
    ]
