# Generated by Django 4.1.7 on 2023-04-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_club_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='meeting_days',
            field=models.CharField(choices=[('SU', 'Sunday'), ('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday')], default='FR', max_length=2),
        ),
    ]
