# Generated by Django 4.1.7 on 2023-04-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_club_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='test',
        ),
    ]
