# Generated by Django 4.1.7 on 2023-04-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_club_google_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='meeting_room',
            field=models.ManyToManyField(blank=True, to='list.meetingrooms'),
        ),
    ]
