# Generated by Django 4.1.7 on 2023-04-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_club_meeting_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='meeting_days',
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.categories'),
        ),
        migrations.AddField(
            model_name='club',
            name='meeting_days',
            field=models.ManyToManyField(to='list.days'),
        ),
    ]
