# Generated by Django 4.1.7 on 2023-04-22 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_club_meeting_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='meeting_room',
        ),
    ]
