# Generated by Django 4.1.7 on 2023-04-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_categories_days_remove_club_meeting_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='picture',
            field=models.ImageField(blank=True, upload_to='./images'),
        ),
    ]
