# Generated by Django 4.1.7 on 2023-04-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_remove_club_meeting_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='meeting_room',
            field=models.ManyToManyField(blank=True, to='list.meetingrooms'),
        ),
    ]
