# Generated by Django 4.1.7 on 2023-04-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_club_meeting_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Days',
        ),
    ]
