# Generated by Django 4.1.7 on 2023-04-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_delete_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.ManyToManyField(to='list.categories'),
        ),
    ]
