# Generated by Django 4.1.7 on 2023-04-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_alter_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='sponsor',
            field=models.JSONField(),
        ),
    ]
