# Generated by Django 4.1.7 on 2023-04-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_remove_club_category_club_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPresidentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_president_name', models.CharField(max_length=30)),
                ('club_president_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='club_president',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.clubpresidentname'),
        ),
    ]
