# Generated by Django 4.1.7 on 2023-04-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_alter_club_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.sponsorname'),
        ),
    ]
