# Generated by Django 4.1.7 on 2023-04-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_sponsorname_alter_club_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='club',
            name='sponsor',
            field=models.ManyToManyField(to='list.sponsorname'),
        ),
    ]
