# Generated by Django 4.1.7 on 2023-04-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_clubpresidentname_club_end_time_club_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.clubpresidentname'),
        ),
        migrations.AlterField(
            model_name='club',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
