# Generated by Django 4.1.7 on 2023-04-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_alter_club_club_president_alter_club_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_president',
        ),
        migrations.AddField(
            model_name='club',
            name='club_president',
            field=models.ManyToManyField(blank=True, to='list.clubpresidentname'),
        ),
    ]
