# Generated by Django 4.1.7 on 2023-04-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_remove_club_sponsor_club_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='sponsor_email',
        ),
        migrations.AddField(
            model_name='sponsorname',
            name='sponsor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
