# Generated by Django 4.1.7 on 2023-04-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_remove_club_sponsor_email_sponsorname_sponsor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorname',
            name='sponsor_email',
            field=models.EmailField(max_length=254),
        ),
    ]
