# Generated by Django 4.1.7 on 2023-04-22 15:45

import datetime
from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_remove_club_club_president_club_club_president'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(16, 30), null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(15, 30), null=True),
        ),
        migrations.AlterField(
            model_name='meetingrooms',
            name='meeting_room_number',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
