# Generated by Django 4.1.7 on 2023-04-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_alter_sponsorname_sponsor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
