# Generated by Django 4.1.7 on 2023-04-22 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_alter_club_end_time_alter_club_recurrences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(16, 30)),
        ),
        migrations.AlterField(
            model_name='club',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(15, 30)),
        ),
    ]
