# Generated by Django 4.1.7 on 2023-04-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_alter_club_end_time_alter_club_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='picture',
            new_name='main_picture',
        ),
    ]
