# Generated by Django 4.1.7 on 2023-04-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_rename_picture_club_main_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='./images')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='other_pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.otherimage'),
        ),
    ]
