# Generated by Django 4.1.7 on 2023-04-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0014_otherimage_club_other_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='other_pictures',
        ),
        migrations.AddField(
            model_name='otherimage',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.club'),
        ),
    ]
