# Generated by Django 4.1.7 on 2023-04-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0015_remove_club_other_pictures_otherimage_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='./mainimages'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='./otherimages'),
        ),
    ]
