# Generated by Django 4.1.7 on 2023-04-23 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0016_alter_club_main_picture_alter_otherimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherimage',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.club'),
        ),
    ]
