# Generated by Django 4.1.7 on 2023-04-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0019_alter_club_main_picture_alter_otherimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='.'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='.'),
        ),
    ]
